<?xml version="1.0"?>
<package format="3">
  <name>grupo01_xarm6_bringup</name>
  <version>1.0.0</version>
  <description>Launch de visualización para la práctica IMT-342.</description>
  <maintainer email="imt342.robotica@example.com">IMT-342 Robótica</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xarm_description</exec_depend>
  <exec_depend>uf_ros_lib</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>rmw_cyclonedds_cpp</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
